apiVersion: v1
kind: Service
metadata:
  labels:
    app: web-service
  name: app-service
spec:
  ports:
  - name: 
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: web
  type: NodePort
